version: '3.8'
services:
  db:
    image: mysql
    container_name: DateCalculation
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: date_calculation
      MYSQL_USER: kuma
      MYSQL_PASSWORD: 2203
    ports:
      - 3306:3306   
    volumes:
      - $PWD/mysql:/docker-entrypoint-initdb.d
      
           